name: Build Release APK

on: 
  push:
    branches: [ main ]  # 触发分支
  workflow_dispatch:    # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode Keystore
      env:
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      run: |
        echo "$KEYSTORE_FILE" | base64 -d > ${{ secrets.KEYSTORE_NAME }}

    - name: Grant Gradle permission
      run: chmod +x ./gradlew  # 授权执行权限

    - name: Build Release APK
      env:
        KEYSTORE_NAME: ${{ secrets.KEYSTORE_NAME }}
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$KEYSTORE_NAME \
          -Pandroid.injected.signing.store.password=$KEYSTORE_PASS \
          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$KEY_PASSWORD

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk
